CREATE TABLE [SYSADM].[TSY_QUERYREPOSITORY](
	ID int IDENTITY(1,1) NOT NULL,
	[NAME] [NVARCHAR](256) NOT NULL,
	[LABEL] [NVARCHAR](256) NOT NULL,
	[DESCRIPTION] [NVARCHAR](2048) NULL,
	[SQL] [NVARCHAR](2048) NOT NULL,
	CONSTRAINT [PK_SYSADM_TSY_QUERYREPOSITORY] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [UC_SYSADM_TSY_QUERYREPOSITORY_NAME] UNIQUE([NAME])
)
